---
- name: Install Java, Maven, and Jenkins
  hosts: jenkins
  become: true
  tasks:
    # This task ensures that the APT package cache is up to date on the target system, which is an important step before installing or upgrading packages using APT.
    - name: Update apt package cache
      apt:
        update_cache: yes

    # This run apt install openjdk-11-jdk command on the target system and installs openjdk on the system
    - name: Install OpenJDK
      apt:
        name: openjdk-11-jdk
        state: present

    #This will install the Maven 
    - name: Install Maven
      apt:
        name: maven
        state: present

    #This dowanloads the jenkins repo validation key
    - name: Download Jenkins repository key
      get_url:
        url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
        dest: "/usr/share/keyrings/jenkins-keyring.asc"
        mode: '0644'

    #This tells task will add jenkins repo in apt source list, ensures that each line is present if not then create"yes",         
    - name: Add Jenkins repository to sources.list.d
      lineinfile:
        path: "/etc/apt/sources.list.d/jenkins.list"
        line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        create: yes

    #Update the package apt for the apt package, updates the cache and fetched the latest list from repo.
    - name: Update apt package cache
      apt:
        update_cache: yes

    
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Download kubectl binary
      get_url:
        url: "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl"
        dest: "/usr/bin/kubectl"
        mode: '0755'
      args:
        creates: /usr/bin/kubectl
