---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-catalog-service
  template:
    metadata:
      labels:
        app: movie-catalog-service
    spec:
      containers:
      - name: movie-catalog-service
        image: adrika1203/movie-catalog-service:1.0  # Replace with your Docker image
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: movie-catalog-service-service
spec:
  selector:
    app: movie-catalog-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

