---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings-data-service
  template:
    metadata:
      labels:
        app: ratings-data-service
    spec:
      containers:
      - name: ratings-data-service
        image: adrika1203/ratings-data-service:1.0
        ports:
        - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: ratings-data-service-service
spec:
  selector:
    app: ratings-data-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083

