apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: adrika1203/discovery-server:1.0  # Replace with your Docker image
        ports:
        - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server-service
spec:
  selector:
    app: discovery-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-catalog-service
  template:
    metadata:
      labels:
        app: movie-catalog-service
    spec:
      containers:
      - name: movie-catalog-service
        image: adrika1203/movie-catalog-service:1.0  # Replace with your Docker image
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: movie-catalog-service-service
spec:
  selector:
    app: movie-catalog-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-info-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-info-service
  template:
    metadata:
      labels:
        app: movie-info-service
    spec:
      containers:
      - name: movie-info-service
        image: adrika1203/movie-info-service:1.0  # Replace with your Docker image
        ports:
        - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: movie-info-service-service
spec:
  selector:
    app: movie-info-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings-data-service
  template:
    metadata:
      labels:
        app: ratings-data-service
    spec:
      containers:
      - name: ratings-data-service
        image: adrika1203/ratings-data-service:1.0  # Replace with your Docker image
        ports:
        - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: ratings-data-service-service
spec:
  selector:
    app: ratings-data-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083

